### ISSUE TITLE
Refactor to allow usage without passing the application account variable

### ISSUE THREAD

**Issue by tkennedy-cf** [Coalfire-CF/terraform-aws-account-setup#17]
**Describe the solution you'd like**
I'd like to be able to use this module with out passing the application account variable. 

This would allow me to create separate kms keys if I want to keep my application kms keys separate from the mgmt account

**Describe alternatives you've considered**

**Additional context**

**Comment by kourosh-forti-hands** [comment]
feed it and empty value. ```application_account_numbers = [""]```

This is a dynamic so its not always required.
