### ISSUE TITLE
Create Cloudtrail s3 buckets as part of account setup

### ISSUE THREAD

**Issue by az-kennedy** [Coalfire-CF/terraform-aws-account-setup#21]
Cloudtrail buckets are often required for using SIEM tools such as Splunk.

**Comment by kourosh-forti-hands** [comment]
this needs to include a flag for the cloudtrail bucket, bc its not always required, as it can be created via org wide actions instead.

**Comment by kourosh-forti-hands** [comment]
add fedramp doc bucket too "${var.resource_prefix}-${var.aws_region}-fedrampdoc"
